### ISSUE TITLE
Convert multiple xml annotation data at a time

### ISSUE THREAD

**Issue by guiaugustoga987** [otamajakusi/yolov5-utils#1]
This example convert a 1 xml annotation data to txt annotation data : 

`python3 yolov5-utils/voc2yolo5_obb.py --path data/car-parking.xml --class-file data/classes.txt`

Is there a way to convert multiple xml files at a time instead of only one ? 

Thanks.

**Comment by otamajakusi** [comment]
Hi, you can use this option. xml **directory** can be specified by `--path`. 
```
python3 yolov5-utils/voc2yolo5_obb.py --path data --class-file data/classes.txt
```
see https://github.com/otamajakusi/yolov5-utils/blob/main/voc2yolo5_obb.py#L96-L97
Thanks!
